name: bula
favicon: null
layout_spectrum: 0.50789
typography_spectrum: 0.18075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f7eb3'
    - '#a5c1cd'
    - '#352832'
    - '#9b9b91'
    - '#8a6d6e'
  brandStrength: 0.25
  lightness: 0.7382870577275753
  saturation: 0.8125
  rhythmicContrast: 0.9583669290877879
purpose: []
